#!/usr/bin/env python3
"""
build_wheel.py — One-command build for the compiled ZenAI Core wheel.

Handles:
  1. Prerequisites check (Cython, setuptools, wheel)
  2. Staging source from local_llm, rag_core, Core, adapters
  3. Cython compilation → .pyd/.so
  4. Wheel packaging (no .py source inside)
  5. Cleanup

Usage:
    python dist_build/build_wheel.py              # default build
    python dist_build/build_wheel.py --clean      # remove all build artifacts
    python dist_build/build_wheel.py --pyc-only   # skip Cython, .pyc fallback

Output:
    dist_build/dist/zenai_core-1.0.0-cp3XX-win_amd64.whl
"""

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).parent.resolve()
PROJECT_ROOT = HERE.parent
STAGE = HERE / "_staging"
DIST = HERE / "dist"


def check_prereqs():
    """Verify build tools are available."""
    missing = []
    for pkg in ["cython", "setuptools", "wheel"]:
        try:
            __import__(pkg)
        except ImportError:
            missing.append(pkg)
    if missing:
        # [X-Ray auto-fix] print(f"Installing missing build tools: {', '.join(missing)}")
        subprocess.check_call([sys.executable, "-m", "pip", "install", *missing, "--quiet"])
    # Verify C compiler (Windows needs MSVC)
    if sys.platform == "win32":
        # Check for MSVC via setuptools (distutils removed in 3.12+)
        try:
            from setuptools._distutils.msvccompiler import MSVCCompiler

            print("  C compiler: MSVC (Visual Studio Build Tools)")
        except ImportError:
            try:
                import distutils.msvccompiler

                print("  C compiler: MSVC (Visual Studio Build Tools)")
            except ImportError:
                print("  WARNING: MSVC not detected. Cython compilation may fail.")
                print("           Install Visual Studio Build Tools with C++ workload.")
    print("  Prerequisites: OK\n")


def clean():
    """Remove all build artifacts."""
    for d in [STAGE, DIST, HERE / "build", HERE / "zenai_core.egg-info"]:
        if d.exists():
            shutil.rmtree(d, ignore_errors=True)
            # [X-Ray auto-fix] print(f"  Removed: {d}")
    # Remove .c files generated by Cython
    for c_file in HERE.rglob("*.c"):
        c_file.unlink()
    print("  Clean complete.\n")


def build_wheel(pyc_only: bool = False):
    """Run the full build pipeline."""
    print("=" * 60)
    print("  ZenAI Core — Compiled Wheel Builder")
    print("=" * 60)

    # Step 1: Prerequisites
    print("\n[1/4] Checking prerequisites...")
    if not pyc_only:
        check_prereqs()
    else:
        print("  Skipping Cython (--pyc-only mode)\n")

    # Step 2: Clean previous build
    print("[2/4] Cleaning previous artifacts...")
    clean()

    # Step 3: Run setup.py bdist_wheel
    print("[3/4] Building wheel...")
    setup_script = HERE / "setup_zenai_core.py"
    if not setup_script.exists():
        print(f"  ERROR: {setup_script} not found!")
        sys.exit(1)

    env = os.environ.copy()
    if pyc_only:
        # Force no-Cython path in setup script
        env["ZENAI_NO_CYTHON"] = "1"

    cmd = [sys.executable, str(setup_script), "bdist_wheel", "--dist-dir", str(DIST)]
    result = subprocess.run(cmd, env=env, cwd=str(HERE))

    if result.returncode != 0:
        print("\n  BUILD FAILED. Check errors above.")
        print("  Common fixes:")
        print("    - Install Visual Studio Build Tools (C++ build tools)")
        print("    - pip install cython setuptools wheel")
        sys.exit(1)

    # Step 4: Strip source from wheel and report
    print("\n[4/4] Verifying output...")
    wheels = list(DIST.glob("zenai_core-*.whl"))
    if not wheels:
        print("  ERROR: No wheel produced!")
        sys.exit(1)

    whl = wheels[0]
    whl_size = whl.stat().st_size / 1024
    # [X-Ray auto-fix] print(f"\n  {'=' * 56}")
    # [X-Ray auto-fix] print(f"    BUILD SUCCESSFUL")
    # [X-Ray auto-fix] print(f"  {'-' * 56}")
    # [X-Ray auto-fix] print(f"    Wheel:  {whl.name}")
    # [X-Ray auto-fix] print(f"    Size:   {whl_size:.0f} KB")
    # [X-Ray auto-fix] print(f"    Path:   {whl}")
    # [X-Ray auto-fix] print(f"  {'-' * 56}")
    # [X-Ray auto-fix] print(f"    Install command for collaborators:")
    # [X-Ray auto-fix] print(f"      pip install {whl.name}")
    # [X-Ray auto-fix] print(f"  {'-' * 56}")
    print(f"    Usage in their code:")
    # [X-Ray auto-fix] print(f"      from rag_core import RAGEngine, HybridSearcher")
    # [X-Ray auto-fix] print(f"      from local_llm import LlamaCppManager, ModelRegistry")
    # [X-Ray auto-fix] print(f"      from Core import QueryRequest, ChatResponse")
    # [X-Ray auto-fix] print(f"      from zenai_adapters import LLMFactory, RAGIntegration")
    # [X-Ray auto-fix] print(f"  {'=' * 56}\n")
    # Verify no .py source leaked into wheel
    import zipfile

    with zipfile.ZipFile(whl) as zf:
        py_files = [n for n in zf.namelist() if n.endswith(".py") and "__init__" not in n]
        if py_files:
            print(f"  WARNING: {len(py_files)} .py files found in wheel:")
            for f in py_files[:5]:
                # [X-Ray auto-fix] print(f"    - {f}")
                pass
            print("  These should be compiled .pyd/.so in production.")
        else:
            print("  Verified: No source .py files in wheel (only __init__.py stubs + .pyd/.so)")

    # Cleanup staging
    if STAGE.exists():
        shutil.rmtree(STAGE, ignore_errors=True)

    return whl


def main():
    parser = argparse.ArgumentParser(description="Build compiled ZenAI Core wheel")
    parser.add_argument("--clean", action="store_true", help="Remove all build artifacts")
    parser.add_argument("--pyc-only", action="store_true", help="Skip Cython, produce .pyc-only wheel (less secure)")
    args = parser.parse_args()

    if args.clean:
        clean()
        return

    build_wheel(pyc_only=args.pyc_only)


if __name__ == "__main__":
    main()
