import asyncio
import logging
import sys
import os

# Setup path
sys.path.append(os.getcwd())

# Config Logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("ScraperDiagnose")


async def diagnose_url(url):
    """Diagnose url."""
    # [X-Ray auto-fix] print(f"\n--- Diagnosing URL: {url} ---")
    try:
        from zena_mode.async_scraper import SafeAsyncScraper
    except ImportError:
        print("Error: import failed")
        return

    # Initialize Scraper
    scraper = SafeAsyncScraper(base_url=url, max_concurrent=1)

    # We use internal methods to just scrape the landing page
    import aiohttp

    async with aiohttp.ClientSession() as session:
        from asyncio import Semaphore

        sem = Semaphore(1)

        print("Fetching page...")
        result = await scraper.scrape_page(session, url, sem)

        if not result:
            print("FAILED: Scraper returned None (timeout or error)")
            return

        content = result["content"]
        title = result["title"]

        # [X-Ray auto-fix] print(f"Title: {title}")
        # [X-Ray auto-fix] print(f"Content Length: {len(content)} chars")
        # [X-Ray auto-fix] print(f"Preview: {content[:500]}...")
        if len(content) < 200:
            print("\n[DIAGNOSIS] ⚠️ Content is very short. Likely a JavaScript-rendered page (SPA).")
            print("Standard Request-based scrapers cannot see content generated by JS.")
        else:
            print("\n[DIAGNOSIS] ✅ Content seems sufficient.")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        url = sys.argv[1]
    else:
        url = "https://spitaljudetean-oradea.ro/"  # From user screenshot

    asyncio.run(diagnose_url(url))
